[project]
name = "library-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.1",
    "pydantic>=2.13.3",
    "pytest>=9.0.3",
    "uvicorn>=0.46.0",
]
[project.scripts]
start = "uvicorn main:app --reload"
